// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ProcessMessage(arg1:string):Promise<void>;

export function RegisterHotKey():Promise<void>;

export function ToggleVisibility():Promise<void>;
